TensorFlow Basics – Learning Outline
1. Introduction to Tensors
What are tensors?

Tensor ranks, shapes, and data types

Creating tensors with tf.constant, tf.Variable, etc.

2. Getting Information from Tensors
Inspecting tensor shape, rank, and type

Using .numpy(), .shape, .dtype, etc.

Indexing and slicing tensors

3. Manipulating Tensors
Basic operations: addition, multiplication, etc.

Reshaping with tf.reshape()

Expanding and squeezing dimensions

Transposing tensors

4. Tensors and NumPy
Interoperability with NumPy

Converting between tensors and NumPy arrays

Performance considerations

5. Using @tf.function
What is @tf.function?

Converting Python functions to TensorFlow graphs

Benefits of using @tf.function

Example usage

6. Using GPUs (or TPUs) with TensorFlow
Checking for GPU/TPU availability

Running operations on GPU/TPU

Best practices for performance

In [2]:
#INTRO TO TENSORS

import tensorflow as tf
print(tf.__version__)


2.18.0


In [3]:
#create tensors with tf.constant
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [5]:
#check the number of dimension of a tensor (ndim stands for number of dimensions )

scalar.ndim

0

In [6]:
#create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [7]:
# check the dimension of our vector
vector.ndim

1

In [8]:
# create a matrix (having more the 1 dim)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [10]:
# dimension of that matrix
matrix.ndim

2

In [17]:
#create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],

                               [4.,3.]], dtype=tf.float16) #specify the datatype

another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 4.,  3.]], dtype=float16)>

In [20]:
another_matrix.ndim

2

In [26]:
# Let's create a tensor
tensor = tf.constant([
    [[1, 2, 3], [2, 3, 3] ],
    [[2, 2, 1], [7, 8, 9]],
    [[3, 4, 2], [2, 6, 8]]
])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 3]],

       [[2, 2, 1],
        [7, 8, 9]],

       [[3, 4, 2],
        [2, 6, 8]]], dtype=int32)>

In [27]:
tensor.ndim

3

##  What We Have Created So Far

- **Scalar**: A single number  
  ➤ 0-D tensor

- **Vector**: A number with direction (e.g., windspeed and direction)  
  ➤ 1-D tensor

- **Matrix**: A 2-dimensional array of numbers  
  ➤ 2-D tensor

- **Tensor**: An n-dimensional array of numbers  
  ➤ A 0-D tensor is a scalar  
  ➤ A 1-D tensor is a vector  
  ➤ A 2-D tensor is a matrix  
  ➤ A 3-D or higher is called a tensor

---

## 🔢 Understanding Tensor Shapes

A tensor's **shape** tells you how many dimensions and how many elements are in each dimension.

Example:

- `shape = (3, 3, 3)`  
  → 3 blocks, each with 3 rows and 3 columns

- `shape = (2, 2, 1)`  
  → 2 blocks, each with 2 rows, and each row has 1 value

Think of it like nested lists:

```python
tf.constant([
  [ [1], [2] ],       # block 1
  [ [3], [4] ]        # block 2
])  # shape = (2, 2, 1)
